### ISSUE TITLE
Mehrfachsendungen gehen nur bei globalen Formaten

### ISSUE THREAD

**Issue by maede97** [smathys/hitobito_cevi#14]
Mehrfachsendungen werden nur bei globalen Etiketten-Formaten berücksichtigt.
Bei eigenen Formaten werden die Mehrfachsendungen nicht berücksichtigt.

**Comment by maede97** [comment]
Wenn ein Export gemacht wird (mit einer universellem Vorlage mit "Mehrfachsendungen vermeiden", wird diese Vorlage sozusagen "nach oben genommen, über einen Divider. Beim nächsten Mal kann diese dann gleich wieder ausgesucht werden und ist prominent oben. Sobald sie aber oben ist, gehen auch dort die Mehrfachsendungen nicht mehr. Falls aber die gleiche Vorlage aus der Liste unter dem Divider ausgelesen wird, gehen die Mehrfachsendungen.

**Comment by smathys** [comment]
Ist leider weitaus komplexer als nur str. und strasse, da es in der Westschweiz auch noch Abkürzungen gibt in den Strassen-Namen, im Tessin wohl auch. Wenn schon würde ich hier bei der Haushaltsadressierung ansetzen, sodass bei allen Personen die gleiche Adresse ob mit str. oder Strasse übernommen wird

**Comment by smathys** [comment]
diese Funktion wird durch die Haushaltsadressierung wohl sowieso verändert.
evtl. re-test auf Testumgebung sinnvoll, ob die Etiketten nun immer korrekt erstellt werden mit dem neuen Feature

**Comment by maede97** [comment]
Habe dies gerade mal ausprobiert. Der Bug wie er hier erfasst ist, wird mit den Haushaltsadressierungs-Änderungen nicht mehr auftreten bei den Adressen.
Die Haushaltsadressierung scheint auch zu funktionieren.
