### ISSUE TITLE
Hinzufügen alternative Email Adresse standardmässig „Versand“ nicht aktivieren

### ISSUE THREAD

**Issue by smathys** [smathys/hitobito_cevi#16]
Wenn eine alternative Email Adresse hinzugefügt wird, könnte die Checkbox für „Versand“ standardmässig nicht deaktiviert werden?
Durch automatische aktivieren der Checkbox, kann diese Information übersehen werden und ist somit fehleranfällig

**Comment by maede97** [comment]
Habe dies gerade schnell ausprobiert. Ist nun deaktiviert, also alles in Ordnung.
