### ISSUE TITLE
Mehrfachsendungen Improvement / Strasse einheitlich

### ISSUE THREAD

**Issue by maede97** [smathys/hitobito_cevi#34]
Die "Mehrfachsendungen" machen ja schon teilweise Probleme (siehe z.B. #14),
Weiter ist das Problem, dass bei Personen, welche im gleichen Haushalt wohnen, auch Probleme auftreten, wenn die Strasse verschieden steht:
Person Hans Muster, Teststrasse 1, 8000 Zürich
Person Franz Muster, Teststr. 1, 800 Zürich
Die Mehrfachsendungs-Funktion erkennt diese zwei nicht als gleich!
Ich sehe da auch noch ein Problem, dass dann bei den Haushaltsadressierungen auftreten könnte.
Ich sehe momentan zwei Lösungen:
1) Die CeviDB erkennt auch den String "str." als "strasse"
2) Die CeviDB bietet eine Funktion, dass bei allen erfassten Personen auf Knopfdruck im Feld Adresse "str." durch "strasse" ersetzt.

**Comment by smathys** [comment]
Ist leider weitaus komplexer als nur str. und strasse, da es in der Westschweiz auch noch Abkürzungen gibt in den Strassen-Namen, im Tessin wohl auch. Wenn schon würde ich hier bei der Haushaltsadressierung ansetzen, sodass bei allen Personen die gleiche Adresse ob mit str. oder Strasse übernommen wird
