### ISSUE TITLE
Kursanmeldungen einsehen AL/SL

### ISSUE THREAD

**Issue by maede97** [smathys/hitobito_cevi#35]
Lobo (Cevi Stäfa) hat mir am STO erzählt, er würde gerne in der Lage sein, alle seine Teilnehmer seiner Stufe zu sehen, welche sich für Kurse/Lager angemeldet haben. Das heisst, er kann dann auf einen Blick sehen, ob er noch Werbung machen muss bei einzelnen Kindern.
Das gleiche könnte dann (meiner Ansicht nach) noch auf Stufe AL für die gesamte Abteilung eingefügt werden.

**Comment by smathys** [comment]
ja im alten Ausbildungstool, Armin konnten die ALs auch nachschauen in welchen Kursen ihre TNs angemeldet waren. 

Im Moment muss man die TNs von hand durchklicken in den Personendetails sieht man dann ja, wenn jemand angemeldet ist. 
Man müsste mal schauen wie aufwendig es ist. Bis letzten Sommer hatten wir schon Mühe, das man innerhalb des Ausbildungsteams sieht, welche Personen zu welchen Kursen angemeldet waren.

**Comment by nchiapol** [comment]
Beim Arbeitsgebiet gibt es das Tab "Ausbildung" dort wird genau die gewünscht Info angezeigt.

**Comment by maede97** [comment]
Erfasst in https://wiki.cevi.ch/index.php/CeviDB
