### ISSUE TITLE
Rollen im People-Export nicht identisch mit Subscription-Export

### ISSUE THREAD

**Issue by nchiapol** [smathys/hitobito_cevi#40]
Rollen im People-Export sind nicht identisch mit Subscription-Export. Der People-Export ist korrekt, der Subscription Export enthält zum Teil alte Rollen.

**Comment by smathys** [comment]
@nchiapol kannst du dies auf der Testumgebung nachvollziehen ob es gelöst ist?

**Comment by smathys** [comment]
gefixed via https://github.com/hitobito/hitobito/issues/423
