### ISSUE TITLE
Kurs erstellen nur mit dem Flag 2. Unterschrift nötig

### ISSUE THREAD

**Issue by smathys** [smathys/hitobito_cevi#53]
in der Region Bern benötigt es keine Unterschrift von TNs > 18. Man möchte den Kurs so erfassen können, dass nur "2.Unterschrift nötig" gelten würde. Also dass nur für TNs < 18 eine Unterschrift nötig ist.

**Comment by nchiapol** [comment]
Mir scheint das technisch eher kompliziert abzubilden. Auch halte ich die Gefahr, dass die resultierenden Infos eher verwirrend sind, für ziemlich gross. Wir machen das bei uns im RV so, dass wir bei Kursen mit mindestalter < 18 beide Unterschriften aktivieren aber bei > 18 TN nicht auf der Unterschrift beharren. (und das auch so kommunizieren). Das funktioniert ziemlich gut.

Persönlich sehe ich hier deshalb keinen dringenden Programmierbedarf.

**Comment by smathys** [comment]
@MrTinnysis wäre das für euch so möglich zu handhaben? habe gerade gesehen, dass Grizzly noch keinen github account hat, deshalb frage ich dich an ;-)

**Comment by tschuepbach** [comment]
Ja dies sollte machbar sein. Dies wäre nur ein «es wäre schön, wenn ...»-Feature gewesen, aber ist nicht dringend nötig.
