### ISSUE TITLE
Neue Rolle «Leiter/ -in» innerhalb der Gruppe «Jungschar/Team»

### ISSUE THREAD

**Issue by tschuepbach** [smathys/hitobito_cevi#54]
Louis und ich haben gestern noch diskutiert, ob innerhalb der Gruppe «Team», auf der Ebene «Jungschar», eine Rolle «Leiter/- in» sinnvoll wäre. Wir finden die bestehenden Rollen zum Teil etwas unbrauchbar. Ohne die "normale" Leiterrolle brauchen viele Ortsgruppen in Bern die Gruppe «Team» nicht und ist daher nutzlos.

![rollen innerhalb team](https://user-images.githubusercontent.com/40494600/41807384-c567a940-76ce-11e8-913a-5b04ea49c20b.PNG)

**Comment by nchiapol** [comment]
Bei der Einführung der DB sind wir davon ausgegangen, dass die Gruppen vom Typ Team für Gremien und Stabsfunktionen verwendet werden. Entsprechend gibt es dort die wichtigsten Stabsfunktionen (die wir evtl. mal über mehrere Ortsgruppen hinweg ansprechen wollen) als definierte Rollen. Für sonstige Gremien sind Leitung und Mitarbeiter/-in vorgesehen. 
Die "normalen" Leiter sind ja bereits in den normalen Gruppen erfasst und brauchen keine extra Rolle mehr. Entsprechend sehe ich den Grund für eine weitere Rolle nicht. Aber vielleicht habe ich euren Use-Case auch einfach nicht verstanden.
