### ISSUE TITLE
Doku Berechtigungen review

### ISSUE THREAD

**Issue by smathys** [smathys/hitobito_cevi#6]
evtl. https://share.cevi-zhshgl.ch/dokuwiki/doku.php?id=db:rights
in eine berechtigungsmatrix umformatieren/schreiben

**Comment by maede97** [comment]
Hitobito / wagon-cevi: Output genommen und in unsere "Sprache" übersetzt.

**Comment by maede97** [comment]
Und habe gerade eine Berechtigungs-Matrix eingefügt!
https://share.cevi-zhshgl.ch/dokuwiki/doku.php?id=db:rights#berechtigungs-matrix

**Comment by smathys** [comment]
super @maede97 genau das wollte ich noch als nächstes vorschlagen :-)
Vielen Dank!
