### ISSUE TITLE
alte Issues durchschauen und Punkte die noch verbessert werden können in gitlab issues umwandeln

### ISSUE THREAD

**Issue by smathys** [smathys/hitobito_cevi#7]
https://share.cevi-zhshgl.ch/dokuwiki/doku.php?id=db:issues
redmine?

**Comment by nchiapol** [comment]
Das muss ich noch machen

**Comment by smathys** [comment]
sorry, dachte ihr habt das am Freitag noch konplett erledigt ;-)

**Comment by nchiapol** [comment]
Habe das nun endlich gemacht.

**Comment by smathys** [comment]
Vielen Dank!
